//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeManagement.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OfficeManagementEntities : DbContext
    {
        public OfficeManagementEntities()
            : base("name=OfficeManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_DepartmentInfo> tbl_DepartmentInfo { get; set; }
        public virtual DbSet<tbl_EmployeeInfo> tbl_EmployeeInfo { get; set; }
        public virtual DbSet<tbl_EmplyoeeAttendance> tbl_EmplyoeeAttendance { get; set; }
        public virtual DbSet<tbl_OfficeInfo> tbl_OfficeInfo { get; set; }
    }
}
